name: ber
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - cpuonly
  - numpy
  - gymnasium
  - hydra-core
  - omegaconf
  - wandb
  - tqdm
  - matplotlib
  - pandas
  - ipykernel
