algo: dqn

# Replay / sampling
replay:
  type: uniform      # uniform | per | ...
  capacity: 1000000
  batch_size: 32
  eps: 1.0e-6

# Exploration
epsilon:
  start: 1.0
  end: 0.05
  decay_steps: 40000

# Optimization
optimizer:
  lr: 1e-4
  weight_decay: 1e-5 

# DQN / DDQN specifics
gamma: 0.99
handle_time_limit_as_terminal: true
train_freq: 4              # gradient step each env step
learning_starts: 500
gradient_steps: 1
max_grad_norm: 10.0

target_update:
  interval: 5000
  tau: 1.0

# Network
model:
  type: mlp
  hidden_sizes: [64, 64]
  activation: relu

# Logging and eVal
log_interval_steps: 1000
eval_episodes: 10
