algo: dqn

# Replay / sampling
replay:
  type: per      # Changed to per
  capacity: 200000
  batch_size: 128
  eps: 1.0e-6
  alpha: 0.6
  beta: 0.4
  beta_anneal_steps: 800000

# Exploration
epsilon:
  start: 1.0
  end: 0.05
  decay_steps: 400000

# Optimization
optimizer:
  lr: 3.0e-4
  weight_decay: 0

# DQN / DDQN specifics
gamma: 0.99
handle_time_limit_as_terminal: true
train_freq: 1              # gradient step each env step
learning_starts: 10000
gradient_steps: 1
max_grad_norm: 10.0

target_update:
  interval: 1
  tau: 0.01

# Network
model:
  type: mlp
  hidden_sizes: [128, 128]
  activation: relu

# Logging and eVal
log_interval_steps: 2000
eval_episodes: 20
