algo: dqn

# Replay / sampling
replay:
  type: per
  capacity: 50000
  batch_size: 128
  eps: 1.0e-6
  alpha: 0.6
  beta: 0.4
  beta_anneal_steps: 500000

  sa_mitigation:
    enabled: false
    method: none   # avg | sample | model |none
    include_self: true
    min_group: 1
    max_group: 0
    update_all_siblings: false

  grouping:
    enabled: false
    type: vqvae
    ckpt_path: "artifacts/vqvae_minatar_breakout.pt"
    device: "cpu"
    cache_size: 200000

# Exploration
epsilon:
  start: 1.0
  end: 0.05
  decay_steps: 500000

# Optimization
optimizer:
  lr: 3.0e-3
  weight_decay: 0

# DQN / DDQN specifics
gamma: 0.99
handle_time_limit_as_terminal: true
train_freq: 1              # gradient step each env step
learning_starts: 5000
gradient_steps: 1
max_grad_norm: 10.0

target_update:
  interval: 1000
  tau: 1.0

# Network
model:
  type: mlp
  activation: relu
  hidden_sizes: [64, 64]
  conv_channels: [16, 32]
  fc_hidden: 128

# Logging and eVal
log_interval_steps: 2000
eval_episodes: 50
