algo: dqn

# Replay / sampling
replay:
  type: per
  capacity: 5000
  batch_size: 32
  eps: 1.0e-6
  alpha: 0.6
  beta: 0.4
  beta_anneal_steps: 200000

  sa_mitigation:
    enabled: false
    method: none   # avg | sample | model |none
    include_self: true
    min_group: 1
    max_group: 0
    update_all_siblings: false

  grouping:
    mode: simhash  # exact_sa | simhash
    hash_bits: 32
    hash_subsample: 512  # 0 => use all dims
    hash_seed: 0

# Exploration
epsilon:
  start: 1.0
  end: 0.05
  decay_steps: 200000

# Optimization
optimizer:
  lr: 1.0e-3
  weight_decay: 0

# DQN / DDQN specifics
gamma: 0.0
handle_time_limit_as_terminal: true
train_freq: 1              # gradient step each env step
learning_starts: 5000
gradient_steps: 1
max_grad_norm: 10.0

target_update:
  interval: 500
  tau: 1.0

# Network
model:
  type: mlp
  activation: relu
  hidden_sizes: [32]
  conv_channels: [16, 32]
  fc_hidden: 128

# Logging and eVal
log_interval_steps: 1000
eval_episodes: 20
